# coding: utf-8
# @email: jiuqiangli@outlook.com

embedding_size: 64
n_layers: [1, 2, 3, 4]
knn_k: 10
is_sparse: True
fusion_coeff: [0.1, 0.2, 0.3, 0.4, 0.5, 0.6, 0.7, 0.8, 0.9, 1.0]
tau: 0.2
cl_weight: [0.001, 0.005, 0.01, 0.05, 0.1]
reg_weight: [5e-6, 5e-7, 5e-8, 5e-9, 5e-10]

hyper_parameters: ["n_layers", "fusion_coeff", "cl_weight", "reg_weight"]